# Generated by Django 5.2.3 on 2025-06-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Thumbnail', models.CharField(max_length=255)),
                ('Language', models.CharField(max_length=50)),
                ('Stage', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('IsPremium', models.BooleanField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.CharField(max_length=255)),
                ('PhotoLink', models.CharField(blank=True, max_length=255, null=True)),
                ('IsLast', models.BooleanField()),
                ('LevelId', models.ForeignKey(db_column='LevelId', on_delete=django.db.models.deletion.CASCADE, to='catalog.levels')),
            ],
            options={
                'db_table': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.users')),
            ],
            options={
                'db_table': 'LessonProgress',
            },
        ),
    ]
