# Generated by Django 5.2.3 on 2025-06-17 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Type', models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple Choice')], max_length=10)),
                ('Answers', models.JSONField()),
                ('VideoLink', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Tag', models.CharField(max_length=100)),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='catalog.users')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.users')),
            ],
            options={
                'db_table': 'CommunityPost',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Likes', models.ManyToManyField(blank=True, related_name='liked_comments', to='catalog.users')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='catalog.postcomment')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.communitypost')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.users')),
            ],
            options={
                'db_table': 'PostComment',
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='Questions',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='catalog.question'),
        ),
    ]
